# Generated by Django 2.2.5 on 2020-08-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_peopleinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='comment_count',
            new_name='commentcount',
        ),
        migrations.RenameField(
            model_name='bookinfo',
            old_name='read_count',
            new_name='readcount',
        ),
    ]
